# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSHScript:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: run ssh command
        env:
          PRIVATE_KEY: ${{ secrets.KEY }}
          HOSTNAME : ec2-13-234-38-29.ap-south-1.compute.amazonaws.com
          USER_NAME : ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key 
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY" ${USER_NAME}@${HOSTNAME} '
          python --version
          '
  
